pull_request_rules:
  - name: Automatically merge Greenkeeper PRs on CI success
    conditions:
      - status-success=Test
      - status-success=greenkeeper/verify
      - author=greenkeeper[bot]
    actions:
      merge:
        method: merge
  - name: Delete head branch after merging PR
    conditions: []
    actions:
      delete_head_branch: {}