name: Test
on: [push]

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1.2.0
        with:
          fetch-depth: 1
      - name: Install
        run: npm install
      - name: Test
        run: npm run test:client
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1.2.0
        with:
          fetch-depth: 1
      - name: Install
        run: npm install
      - name: Test
        run: npm run test:server
